@startuml

class AAUOC{
newLocation(l: Location):void
newEvent(e: Event):void
newPerson(p: Person):void
informEvent(e: Event): void
register(m: Member,e:Event):void
}
class Location{
description:String
address:String
}
class Event{
date:Date
description:String
assign(l: Location):void
}
class Person{
name:String
}
class Member{
e-mail:String
}
class BoardMember
class BoardMeeting
class Conference{
max_attendees:Integer
}

AAUOC <|-- "0..*" Location
AAUOC <|-- "0..*" Event
AAUOC <|-- "0..*" Person
Person <|-- Member
Member <|-- BoardMember
Event <|-- BoardMeeting
Event "0..*" -- "1" Location :isLocated In
Member "0..*" -- "0..*" Event : attends To
BoardMember "0..*" -- "0..*" BoardMeeting : attends To
Person "0..*" -- "0..*" Conference : attends To
(Event, BoardMeeting) -- Conference

@enduml